-- CGMessageRegistry;
-- @author crazyjohn;
-- register CGMessage

-- CGplayerMessage
CGPlayerMessage = requireNewMessage("CGPlayerMessage")
-- -- CGhumanMessage
-- CGHumanMessage = requireNewMessage("CGHumanMessage")
-- -- CGchatMessage
-- CGChatMessage = requireNewMessage("CGChatMessage")
-- -- CGbuildingMessage
-- CGBuildingMessage = requireNewMessage("CGBuildingMessage")
-- -- CGbagMessage
-- CGBagMessage = requireNewMessage("CGBagMessage")
-- -- CGmallMessage
-- CGMallMessage = requireNewMessage("CGMallMessage")
-- -- CGbulletinMessage
-- CGBulletinMessage = requireNewMessage("CGBulletinMessage")
-- -- CGcdMessage
-- CGCdMessage = requireNewMessage("CGCdMessage")
-- -- CGquestMessage
-- CGQuestMessage = requireNewMessage("CGQuestMessage")
-- -- CGshopMessage
-- CGShopMessage = requireNewMessage("CGShopMessage")
-- -- CGlevyMessage
-- CGLevyMessage = requireNewMessage("CGLevyMessage")
-- -- CGfriendMessage
-- CGFriendMessage = requireNewMessage("CGFriendMessage")
-- -- CGrankMessage
-- CGRankMessage = requireNewMessage("CGRankMessage")
-- -- CGmailMessage
-- CGMailMessage = requireNewMessage("CGMailMessage")
-- -- CGitemMessage
-- CGItemMessage = requireNewMessage("CGItemMessage")
-- -- CGhoroscopeMessage
-- CGHoroscopeMessage = requireNewMessage("CGHoroscopeMessage")
-- -- CGgemMessage
-- CGGemMessage = requireNewMessage("CGGemMessage")
-- -- CGtechnologyMessage
-- CGTechnologyMessage = requireNewMessage("CGTechnologyMessage")
-- -- CGbattleMessage
-- CGBattleMessage = requireNewMessage("CGBattleMessage")
-- -- CGtrainingMessage
-- CGTrainingMessage = requireNewMessage("CGTrainingMessage")
-- -- CGcrystalexchangeMessage
-- CGCrystalexchangeMessage = requireNewMessage("CGCrystalexchangeMessage")
-- -- CGloginrewardMessage
-- CGLoginrewardMessage = requireNewMessage("CGLoginrewardMessage")
-- -- CGonlinerewardMessage
-- CGOnlinerewardMessage = requireNewMessage("CGOnlinerewardMessage")
-- -- CGturntableMessage
-- CGTurntableMessage = requireNewMessage("CGTurntableMessage")
-- -- CGguideMessage
-- CGGuideMessage = requireNewMessage("CGGuideMessage")
-- -- CGskillMessage
-- CGSkillMessage = requireNewMessage("CGSkillMessage")
-- -- CGstageMessage
-- CGStageMessage = requireNewMessage("CGStageMessage")
-- -- CGvipMessage
-- CGVipMessage = requireNewMessage("CGVipMessage")
-- -- CGantiindulgeMessage
-- CGAntiindulgeMessage = requireNewMessage("CGAntiindulgeMessage")
-- -- CGquestionMessage
-- CGQuestionMessage = requireNewMessage("CGQuestionMessage")
-- -- CGcostnotifyMessage
-- CGCostnotifyMessage = requireNewMessage("CGCostnotifyMessage")
-- -- CGarenaMessage
-- CGArenaMessage = requireNewMessage("CGArenaMessage")
-- -- CGexpeditebuyMessage
-- CGExpeditebuyMessage = requireNewMessage("CGExpeditebuyMessage")
-- -- CGmeditationMessage
-- CGMeditationMessage = requireNewMessage("CGMeditationMessage")
-- -- CGbossMessage
-- CGBossMessage = requireNewMessage("CGBossMessage")
-- -- CGelitestageMessage
-- CGElitestageMessage = requireNewMessage("CGElitestageMessage")
-- -- CGactivityMessage
-- CGActivityMessage = requireNewMessage("CGActivityMessage")
-- -- CGgmquestionMessage
-- CGGmquestionMessage = requireNewMessage("CGGmquestionMessage")
-- -- CGrewardMessage
-- CGRewardMessage = requireNewMessage("CGRewardMessage")
-- -- CGmineMessage
-- CGMineMessage = requireNewMessage("CGMineMessage")
-- -- CGhelperMessage
-- CGHelperMessage = requireNewMessage("CGHelperMessage")
-- -- CGautobattleMessage
-- CGAutobattleMessage = requireNewMessage("CGAutobattleMessage")
-- -- CGhonourshopMessage
-- CGHonourshopMessage = requireNewMessage("CGHonourshopMessage")
-- -- CGgiftMessage
-- CGGiftMessage = requireNewMessage("CGGiftMessage")
-- -- CGfosterMessage
-- CGFosterMessage = requireNewMessage("CGFosterMessage")
-- -- CGrefineMessage
-- CGRefineMessage = requireNewMessage("CGRefineMessage")
-- -- CGmatchbattleMessage
-- CGMatchbattleMessage = requireNewMessage("CGMatchbattleMessage")
-- -- CGfunctionhelperMessage
-- CGFunctionhelperMessage = requireNewMessage("CGFunctionhelperMessage")
-- -- CGwarriorMessage
-- CGWarriorMessage = requireNewMessage("CGWarriorMessage")
-- -- CGbattleguideMessage
-- CGBattleguideMessage = requireNewMessage("CGBattleguideMessage")
-- -- CGrechargetxMessage
-- CGRechargetxMessage = requireNewMessage("CGRechargetxMessage")
-- -- CGyellowvipMessage
-- CGYellowvipMessage = requireNewMessage("CGYellowvipMessage")
-- -- CGtitleMessage
-- CGTitleMessage = requireNewMessage("CGTitleMessage")
-- -- CGlegionMessage
-- CGLegionMessage = requireNewMessage("CGLegionMessage")
-- -- CGgodsoulMessage
-- CGGodsoulMessage = requireNewMessage("CGGodsoulMessage")
-- -- CGprisonMessage
-- CGPrisonMessage = requireNewMessage("CGPrisonMessage")
-- -- CGabattoirMessage
-- CGAbattoirMessage = requireNewMessage("CGAbattoirMessage")
-- -- CGspriteMessage
-- CGSpriteMessage = requireNewMessage("CGSpriteMessage")
-- -- CGbloodtempleMessage
-- CGBloodtempleMessage = requireNewMessage("CGBloodtempleMessage")
-- -- CGsignMessage
-- CGSignMessage = requireNewMessage("CGSignMessage")
-- -- CGrechargeMessage
-- CGRechargeMessage = requireNewMessage("CGRechargeMessage")
-- -- CGmagicMessage
-- CGMagicMessage = requireNewMessage("CGMagicMessage")
-- -- CGfactionMessage
-- CGFactionMessage = requireNewMessage("CGFactionMessage")
-- -- CGmarsMessage
-- CGMarsMessage = requireNewMessage("CGMarsMessage")
-- -- CGtargetMessage
-- CGTargetMessage = requireNewMessage("CGTargetMessage")
-- -- CGlegionbossMessage
-- CGLegionbossMessage = requireNewMessage("CGLegionbossMessage")
-- -- CGlegionmineMessage
-- CGLegionmineMessage = requireNewMessage("CGLegionmineMessage")
-- -- CGnostrumMessage
-- CGNostrumMessage = requireNewMessage("CGNostrumMessage")
-- -- CGescortMessage
-- CGEscortMessage = requireNewMessage("CGEscortMessage")
-- -- CGpredictMessage
-- CGPredictMessage = requireNewMessage("CGPredictMessage")
